import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
normal = { family = "Inconsolata Nerd Font", style = "Regular" }
italic = { family = "Inconsolata Nerd Font", style = "Italic" }
bold = { family = "Inconsolata Nerd Font", style = "Bold" }
bold_italic = { family = "Inconsolata Nerd Font", style = "BoldItalic" }
size = 14.5

[mouse]
# enabled = true
hide_when_typing = true

[keyboard]
bindings = [
    { key = "C", mods = "Control|Shift", action = "Copy" },
    { key = "V", mods = "Control|Shift", action = "Paste" },
    { key = "K", mods = "Control|Shift", action = "IncreaseFontSize" },
    { key = "J", mods = "Control|Shift", action = "DecreaseFontSize" },
]

[clipboard]
enable = true
copy = { command = "xclip -selection clipboard" }
paste = { command = "xclip -selection clipboard -o" }

[window]
dimensions = { columns = 80, lines = 24 }
position = { x = 0.5, y = 0.5 }
startup_mode = "windowed"

[scrolling]
history = 10000
auto_scroll = true

[cursor]
style = "Block"
unfocused_hollow = true

[shell]
program = "/bin/zsh"
args = ["--login"]

[bell]
animation = "EaseOutExpo"
duration = 0

[decorations]
button_color = '0x444B6A'
drag_area_width = 16

[hinting]
enabled = true
