import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
# normal = { family = "Inconsolata Nerd Font", style = "Regular" }
# italic = { family = "Inconsolata Nerd Font", style = "Italic" }
# bold = { family = "Inconsolata Nerd Font", style = "Bold" }
# bold_italic = { family = "Inconsolata Nerd Font", style = "BoldItalic" }
size = 10

[keyboard]
bindings = [
    { key = "C", mods = "Control|Shift", action = "Copy" },
    { key = "V", mods = "Control|Shift", action = "Paste" },
    { key = "K", mods = "Control|Shift", action = "IncreaseFontSize" },
    { key = "J", mods = "Control|Shift", action = "DecreaseFontSize" },
]

# [clipboard]
# enable = true
# copy = { command = "xclip -selection clipboard" }
# paste = { command = "xclip -selection clipboard -o" }

