import = [
  "~/.config/alacritty/themes/catppuccin-frappe.toml"
]

[font]
# normal.family = "Inconsolata LGC Nerd Font"
normal.family = "JetBrains Mono NL Nerd Font Propo"
offset.x = 0
offset.y = 5
size = 16.5

[keyboard]
bindings = [
    { key = "C", mods = "Control|Shift", action = "Copy" },
    { key = "V", mods = "Control|Shift", action = "Paste" },
    { key = "K", mods = "Control|Shift", action = "IncreaseFontSize" },
    { key = "J", mods = "Control|Shift", action = "DecreaseFontSize" },
]

[selection]
save_to_clipboard = true

