import = [
  # "~/.config/alacritty/themes/dreamsof.toml"
  # "~/.config/alacritty/themes/catppuccin-latte.toml"
  "~/.config/alacritty/themes/sweetie_light.toml"
]

live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 15

[font.bold]
family = "Inconsolata LGC Nerd Font Propo"
style = "bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Inconsolata LGC Nerd Font Propo"

[font.normal]
family = "Inconsolata LGC Nerd Font Propo"
style = "Regular"

[font.offset]
x = 0
y = 0

[window]
padding.x = 0
padding.y = 0
dynamic_padding = true
decorations = "Full"
dynamic_title = true
startup_mode = "Windowed"
opacity = 1

[window.dimensions]
columns = 160
lines = 80

# [shell]
# program = "/bin/zsh"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 100000

[keyboard]
bindings = [
    { key = "C", mods = "Control|Shift", action = "Copy" },
    { key = "V", mods = "Control|Shift", action = "Paste" },
    { key = "K", mods = "Control|Shift", action = "IncreaseFontSize" },
    { key = "J", mods = "Control|Shift", action = "DecreaseFontSize" },
]

[selection]
save_to_clipboard = true

[cursor]
blink_interval = 500
blink_timeout = 5
unfocused_hollow = false

[cursor.style]
blinking = "off"
shape = "Block"

[env]
ENV = "xterm-256color"
