#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

mkdir -p $HOME/.config
mkdir -p $HOME/.config/alacritty/themes

create_symlink() {
    local source_file=$1
    local target_file=$2

    if [ -e "$target_file" ]; then
        rm -rf $target_file
    fi

    ln -sf "$source_file" "$target_file"
}

create_symlink "$DOTFILES/tmux/tmux.conf" "$HOME/.config/tmux/tmux.conf"
create_symlink "$DOTFILES/nvim" "$HOME/.config/nvim"
create_symlink "$DOTFILES/phpactor" "$HOME/.config/phpactor"
create_symlink "$DOTFILES/alacritty/alacritty.toml" "$HOME/.config/alacritty/alacritty.toml"
create_symlink "$DOTFILES/alacritty/themes/catppuccin-frappe.toml" "$HOME/.config/alacritty/themes/catppuccin-frappe.toml"
create_symlink "$DOTFILES/alacritty/themes/catppuccin-mocha.toml" "$HOME/.config/alacritty/themes/catppuccin-mocha.toml"
create_symlink "$DOTFILES/i3/config" "$HOME/.config/i3/config"
create_symlink "$DOTFILES/i3status/config" "$HOME/.config/i3status/config"
